### ISSUE TITLE
issue when working with MBProgressHUD

### ISSUE THREAD

**Issue by 1037390459** [qmathe/DropDownMenuKit#28]
on cell.menuAction selector like this:
func choose(_ sender: AnyObject) {
		titleView.toggleMenu()
                showHud();
                hideHud();
	}
and the dropMenu animation will be strange.

**Comment by qmathe** [comment]
Hi,

I modified `ViewController.choose(_:)` in the project example and **MBProgressHUD** seems to be working fine:

```Swift
	@IBAction func choose(_ sender: AnyObject) {
		titleView.title = (sender as! DropDownMenuCell).textLabel!.text

		// Don't show HUD on initial selection (see selectCell() in prepareNavigationBarMenu())
		guard !navigationBarMenu.isHidden else { return }

		guard let navigationView = self.navigationController?.view else { return }
		let hud = MBProgressHUD.showAdded(to: navigationView, animated: true)

		DispatchQueue.global(qos: .background).async {
			sleep(3)
			DispatchQueue.main.async {
				hud.hide(animated: true)
			}
		}
	)
```

You might want to check the following points:
- add the HUD above `DropDownMenu` view (e.g. root view or navigation view), otherwise the HUD won't prevent user touches to be sent to the menu
  - a tap in the menu might end up being closing it instead of selecting a cell, if the HUD is not inserted correctly into the view hierarchy
 - be careful with initial selection if you don't want the HUD to be shown when the menu appears on screen
- don't call `hideHUD()` immediately after `showHUD()` without any delay to ensure the animation looks good

Here is a screenshot:

![Simulator Screen Shot - iPhone Xʀ - 2019-05-02 at 16 34 07](https://user-images.githubusercontent.com/74360/57084017-c89e8800-6cf9-11e9-9402-21100a90b9d1.png)

**Comment by qmathe** [comment]
I'm closing this issue. If it's still a problem, please let me know.
